Update cs2-all-build.yml

diff --git a/.github/workflows/cs2-all-build.yml b/.github/workflows/cs2-all-build.yml
--- a/.github/workflows/cs2-all-build.yml
+++ b/.github/workflows/cs2-all-build.yml
@@ -508,9 +508,9 @@ jobs:
         uses: jurplel/install-qt-action@v4
         with:
           version: 6.8.*
-          modules: 'qtcharts'
           extra: '--external 7z'
-
+ #         modules: 'qtcharts'
+ 
       - name: Clone CaptureStream2
         run: |
           git clone https://github.com/CSReviser/CaptureStream2.git
@@ -528,7 +528,7 @@ jobs:
 
       - name: Prepare CaptureStream2 executable
         run: |
-          wget -qO FFmpeg.tar.gz https://github.com/CSReviser/ffmpeg-build/releases/download/7.1.1/ffmpeg-macos-universal.tar.gz || { echo "Failed to download FFmpeg"; exit 1; }
+          wget -qO FFmpeg.tar.gz https://github.com/CSReviser/ffmpeg-build/releases/download/8.0/ffmpeg-macos-universal.tar.gz || { echo "Failed to download FFmpeg"; exit 1; }
           tar -xzvf FFmpeg.tar.gz ffmpeg
           cp ffmpeg ./build/CaptureStream2.app/Contents/MacOS/ 
           cp CaptureStream2/icon.icns ./build/CaptureStream2.app/Contents/Resources/
