Update cs2-ubuntu.yml

diff --git a/.github/workflows/cs2-ubuntu.yml b/.github/workflows/cs2-ubuntu.yml
--- a/.github/workflows/cs2-ubuntu.yml
+++ b/.github/workflows/cs2-ubuntu.yml
@@ -54,11 +54,10 @@ jobs:
             -w /work/CaptureStream2 \
             --env HOST_UID=${{ steps.userinfo.outputs.uid }} \
             --env HOST_GID=${{ steps.userinfo.outputs.gid }} \
-            --env PATH="/opt/qt6-static/bin:/usr/bin:/bin:/usr/local/bin" \
+            --env PATH="/opt/qt6-static/bin:/usr/bin:/bin:/usr/local/bin:/opt/qt6-static/libexec:$PATH" \
             ${{ env.IMAGE_NAME }} \
             bash -c "
               mkdir -p build && cd build && \
-              export PATH="/opt/qt6-static/bin:/opt/qt6-static/libexec:$PATH" && \
               qt-cmake .. || true && \
               echo "----- CMakeError.log -----" && cat /work/CaptureStream2/build/CMakeCache.txt || true && \
               echo "----- CMakeError.log -----" && cat /work/CaptureStream2/build/CMakeFiles/CMakeError.log || true && \
@@ -75,8 +74,8 @@ jobs:
         shell: bash
         run: |
           cd CaptureStream2/build
-          qt-cmake .. || true
-          echo "----- CMakeError.log -----" && cat ./CMakeCache.txt || true && \
+              cmake --build . --parallel || true
+          echo "----- CMakeError.log -----" && cat ./CMakeCache.txt || true 
           echo "----- CMakeError.log -----" && cat ./CMakeFiles/CMakeError.log || true && \
           echo "----- CMakeOutput.log -----" && cat ./CMakeFiles/CMakeOutput.log || true 
           zip -r "CaptureStream-ubuntu-${{ github.event.inputs.yyyymmdd }}.zip" LinCaptureStream2 && \
