Update cs2-all-build.yml

diff --git a/.github/workflows/cs2-all-build.yml b/.github/workflows/cs2-all-build.yml
--- a/.github/workflows/cs2-all-build.yml
+++ b/.github/workflows/cs2-all-build.yml
@@ -536,7 +536,7 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-  mac_qt6.85_build:
+  mac_qt6_8_build:
     runs-on: macos-15
     needs: mac_build
 
@@ -562,7 +562,7 @@ jobs:
       - name: Install Qt
         uses: jurplel/install-qt-action@v4
         with:
-          version: 6.2.*
+          version: 6.8.*
           extra: '--external 7z'
 #          modules: 'qtcharts'
 
@@ -576,7 +576,7 @@ jobs:
       - name: qmake
         run: |
           cd CaptureStream2
-          qmake -makefile CaptureStream2.pro QMAKE_APPLE_DEVICE_ARCHS="x86_64"
+          qmake -makefile CaptureStream2.pro QMAKE_APPLE_DEVICE_ARCHS="x86_64;arm64"
           make
           wget -qO FFmpeg.7z https://evermeet.cx/ffmpeg/ffmpeg-7.1.1.7z
           7z e FFmpeg.7z ffmpeg -o./CaptureStream2.app/Contents/MacOS/
@@ -645,7 +645,7 @@ jobs:
 
       - name: Prepare CaptureStream2 executable
         run: |
-          wget -qO FFmpeg.tar.gz https://github.com/CSReviser/ffmpeg-build/releases/download/8.0/ffmpeg-macos-universal.tar.gz || { echo "Failed to download FFmpeg"; exit 1; }
+          wget -qO FFmpeg.tar.gz https://github.com/CSReviser/ffmpeg-build/releases/download/9.0.2/ffmpeg-macos-universal.tar.gz || { echo "Failed to download FFmpeg"; exit 1; }
           tar -xzvf FFmpeg.tar.gz ffmpeg
           cp ffmpeg ./build/CaptureStream2.app/Contents/MacOS/ 
           cp CaptureStream2/icon.icns ./build/CaptureStream2.app/Contents/Resources/
@@ -713,10 +713,8 @@ jobs:
 
       - name: Prepare CaptureStream2 executable
         run: |
-          curl -L -A "Mozilla/5.0" \
-          -o ffmpeg8arm.zip \
-          https://www.osxexperts.net/ffmpeg81arm.zip
-          7z e ffmpeg8arm.zip ffmpeg -o./build/CaptureStream2.app/Contents/MacOS/ 
+          wget -qO FFmpeg.zip https://github.com/CSReviser/ffmpeg-build/releases/download/9.0.2/ffmpeg-arm-static.zip || { echo "Failed to download FFmpeg"; exit 1; }
+          7z e FFmpeg.zip ffmpeg -o./build/CaptureStream2.app/Contents/MacOS/ 
           cp CaptureStream2/icon.icns ./build/CaptureStream2.app/Contents/Resources/
           cp CaptureStream2/qss_files/stylesheet-mac.qss ./build/CaptureStream2.app/Contents/MacOS/
 
