Update cs2-ubuntu.yml

diff --git a/.github/workflows/cs2-ubuntu.yml b/.github/workflows/cs2-ubuntu.yml
--- a/.github/workflows/cs2-ubuntu.yml
+++ b/.github/workflows/cs2-ubuntu.yml
@@ -60,6 +60,7 @@ jobs:
               mkdir -p build && cd build && \
               export PATH="/opt/qt6-static/bin:/opt/qt6-static/libexec:$PATH" && \
               qt-cmake .. || true && \
+              echo "----- CMakeError.log -----" && cat /work/CaptureStream2/build/CMakeCache.txt || true && \
               echo "----- CMakeError.log -----" && cat /work/CaptureStream2/build/CMakeFiles/CMakeError.log || true && \
               echo "----- CMakeOutput.log -----" && /work/CaptureStream2/build/CMakeFiles/CMakeOutput.log || true && \
               cmake --build . --parallel && \
