Update cs2-macOS.yml

diff --git a/.github/workflows/cs2-macOS.yml b/.github/workflows/cs2-macOS.yml
--- a/.github/workflows/cs2-macOS.yml
+++ b/.github/workflows/cs2-macOS.yml
@@ -1,4 +1,4 @@
-name: 1. MacOS qt6.10.2 Universal cmake C/C++ CI
+name: 1. MacOS qt6.11.0 AppleSilicon cmake C/C++ CI
 
 on:
   workflow_dispatch:
@@ -13,12 +13,12 @@ jobs:
 
     steps:
     - name: Checkout repository
-      uses: actions/checkout@v4
+      uses: actions/checkout@v6
 
     - name: Install Qt
       uses: jurplel/install-qt-action@v4
       with:
-        version: '6.10.*'
+        version: '6.11.*'
         extra: '--external 7z'
 #        modules: 'qtcharts'
         
@@ -33,19 +33,24 @@ jobs:
     - name: Configure CMake
       run: |
         mkdir build
-        cmake -S CaptureStream2 -B build -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64"
-
+        cmake -S CaptureStream2 -B build -DCMAKE_OSX_ARCHITECTURES="arm64"
+#        cmake -S CaptureStream2 -B build -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64"
+        
     - name: Build with Make
       run: cmake --build build --parallel
 
     - name: Prepare CaptureStream2 executable
       run: |
-        wget -qO FFmpeg.tar.gz https://github.com/CSReviser/ffmpeg-build/releases/download/8.0/ffmpeg-macos-universal.tar.gz || { echo "Failed to download FFmpeg"; exit 1; }
-        tar -xzvf FFmpeg.tar.gz ffmpeg
-        cp ffmpeg ./build/CaptureStream2.app/Contents/MacOS/ 
+        wget -qO ffmpeg8arm.zip https://www.osxexperts.net/ffmpeg81arm.zip
+        7z e ffmpeg8arm.zip ffmpeg -o./CaptureStream2.app/Contents/MacOS/
         cp CaptureStream2/icon.icns ./build/CaptureStream2.app/Contents/Resources/
         cp CaptureStream2/qss_files/stylesheet-mac.qss ./build/CaptureStream2.app/Contents/MacOS/
 
+#        wget -qO FFmpeg.tar.gz https://github.com/CSReviser/ffmpeg-build/releases/download/8.0/ffmpeg-macos-universal.tar.gz || { echo "Failed to download FFmpeg"; exit 1; }
+#        wget -qO FFmpeg.tar.gz https://github.com/CSReviser/ffmpeg-build/releases/download/8.0/ffmpeg-macos-universal.tar.gz || { echo "Failed to download FFmpeg"; exit 1; }
+#        tar -xzvf FFmpeg.tar.gz ffmpeg
+#        cp ffmpeg ./build/CaptureStream2.app/Contents/MacOS/ 
+        
     - name: Create MacCaptureStream2 directory
       run: |
         mkdir -p build/MacCaptureStream2
