cs2-win-arm.yml を更新

diff --git a/.github/workflows/cs2-win-arm.yml b/.github/workflows/cs2-win-arm.yml
--- a/.github/workflows/cs2-win-arm.yml
+++ b/.github/workflows/cs2-win-arm.yml
@@ -17,6 +17,11 @@ jobs:
       - name: Checkout this repo
         uses: actions/checkout@v4
 
+      - name: Show qt.toolchain.cmake contents
+        run: |
+          echo "----- qt.toolchain.cmake -----"
+          cat /opt/qt6-arm/lib/cmake/Qt6/qt.toolchain.cmake || echo "File not found"
+
       - name: Clone CaptureStream2
         run: |
           git clone https://github.com/CSReviser/CaptureStream2.git
