Update cs2-ubuntu.yml

diff --git a/.github/workflows/cs2-ubuntu.yml b/.github/workflows/cs2-ubuntu.yml
--- a/.github/workflows/cs2-ubuntu.yml
+++ b/.github/workflows/cs2-ubuntu.yml
@@ -44,8 +44,8 @@ jobs:
               qt-cmake .. \
               -DQT_DEBUG_FIND_PACKAGE=ON \
               -DCMAKE_EXE_LINKER_FLAGS='-static -lxcb -lXau -lXdmcp -lxcb-util' || true && \
-              echo "----- CMakeError.log -----" && cat CMakeFiles/CMakeError.log || true && \
-              echo "----- CMakeOutput.log -----" && cat CMakeFiles/CMakeOutput.log || true && \
+              echo "----- CMakeError.log -----" && cat /work/CaptureStream2/build/CMakeFiles/CMakeError.log || true && \
+              echo "----- CMakeOutput.log -----" && /work/CaptureStream2/build/CMakeFiles/CMakeOutput.log || true && \
               cmake --build . --parallel && \
               mkdir -p build/LinCaptureStream2 && \
               mv CaptureStream2 build/LinCaptureStream2/ && \
