Update cs2-qt5-all-build.yml

diff --git a/.github/workflows/cs2-qt5-all-build.yml b/.github/workflows/cs2-qt5-all-build.yml
--- a/.github/workflows/cs2-qt5-all-build.yml
+++ b/.github/workflows/cs2-qt5-all-build.yml
@@ -1,5 +1,6 @@
 name: 0-2. Qt5 Build CaptureStream2 for macOS and Windows
 
+
 on:
   workflow_dispatch:
     inputs:
@@ -7,15 +8,92 @@ on:
         description: 'Release date (yyyymmdd)'
         required: true
 
+env:
+  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
+
 jobs:
-  appimage:
-    runs-on: ubuntu-22.04-arm
-    container:
-      image: ghcr.io/csreviser/qt6-static-arm:latest
+  mac_build:
+    runs-on: macos-26
+    outputs:
+      tag: ${{ steps.setvars.outputs.tag }}
+      title: ${{ steps.setvars.outputs.title }}
+
+    steps:
+      - name: Set release variables
+        id: setvars
+        run: |
+          tag=${{ github.event.inputs.yyyymmdd }}
+          title="${tag:0:4}/${tag:4:2}/${tag:6:2}版リリース"
+          echo "tag=$tag" >> $GITHUB_OUTPUT
+          echo "title=$title" >> $GITHUB_OUTPUT
+
+      - name: Checkout
+        uses: actions/checkout@v6
+
+      - name: Install Qt
+        uses: jurplel/install-qt-action@v4
+        with:
+          version: 6.11.0
+          extra: '--external 7z'
+#          modules: 'qtcharts'
+
+      - name: Clone CaptureStream2
+        run: |
+          git clone https://github.com/CSReviser/CaptureStream2.git
+          cd CaptureStream2
+          git checkout feature
+          git submodule update --init --recursive
+
+      - name: Configure CMake
+        run: |
+          mkdir build
+          cmake -S CaptureStream2 -B build -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64"
+
+      - name: Build with Make
+        run: cmake --build build --parallel
+
+      - name: Prepare CaptureStream2 executable
+        run: |
+          wget -qO FFmpeg.tar.gz https://github.com/CSReviser/ffmpeg-build/releases/download/8.0/ffmpeg-macos-universal.tar.gz || { echo "Failed to download FFmpeg"; exit 1; }
+          tar -xzvf FFmpeg.tar.gz ffmpeg
+          cp ffmpeg ./build/CaptureStream2.app/Contents/MacOS/ 
+          cp CaptureStream2/icon.icns ./build/CaptureStream2.app/Contents/Resources/
+          cp CaptureStream2/qss_files/stylesheet-mac.qss ./build/CaptureStream2.app/Contents/MacOS/
+
+      - name: Create MacCaptureStream2 directory
+        run: |
+          mkdir -p build/tmp/MacCaptureStream2
+          mv build/CaptureStream2.app build/tmp/MacCaptureStream2/
+          cp -r CaptureStream2/qss_files/License build/tmp/MacCaptureStream2/
+          
+      - name: Create DMG file
+        run: |
+          cd build
+          hdiutil create -volname MacCaptureStream2 \
+                      -srcfolder tmp \
+                      -ov -format UDZO \
+                      "CaptureStream2-MacOS-${{ github.event.inputs.yyyymmdd }}.dmg"
+
+      - name: Format release title
+        id: format_date
+        run: |
+          yyyy=${{ github.event.inputs.yyyymmdd }} 
+          echo "title=${yyyy:0:4}/${yyyy:4:2}/${yyyy:6:2}版リリース" >> "$GITHUB_OUTPUT"
+
+      - name: Upload DMG to GitHub Release
+        uses: softprops/action-gh-release@v2
+        with:
+          files: build/CaptureStream2-MacOS-${{ github.event.inputs.yyyymmdd }}.dmg
+          tag_name: ${{ github.event.inputs.yyyymmdd }}
+          name: ${{ steps.format_date.outputs.title }}
+          body: "Qt 6.11.0 build test"
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
 
   wim_qt5_build:
     runs-on: ubuntu-latest
+    needs: mac_build
     container:
       image: ghcr.io/csreviser/qt5-mxe-static:5.15.18
 
@@ -80,6 +158,7 @@ jobs:
 
   wim_x68_qt5_build:
     runs-on: ubuntu-latest
+    needs: mac_build
     container:
       image: ghcr.io/csreviser/qt5-mxe-x86-static:5.15.18
 
@@ -144,7 +223,7 @@ jobs:
             
   mac_qt5_build:
     runs-on: macos-15
-
+    needs: mac_build
     steps:
       - name: Set release variables
         id: setvars
@@ -209,6 +288,3 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-          tag_name: ${{ needs.mac_build.outputs.tag }}
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
