Update cs2-all-build.yml

diff --git a/.github/workflows/cs2-all-build.yml b/.github/workflows/cs2-all-build.yml
--- a/.github/workflows/cs2-all-build.yml
+++ b/.github/workflows/cs2-all-build.yml
@@ -501,13 +501,6 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v4
 
-      - name: Mark repo as safe
-        run: git config --global --add safe.directory "${GITHUB_WORKSPACE}"
-
-      - name: Update GitHub CLI
-        run: |
-          brew install gh || brew upgrade gh
-
       - name: Install Qt
         uses: jurplel/install-qt-action@v4
         with:
@@ -533,7 +526,7 @@ jobs:
       - name: Prepare CaptureStream2 executable
         run: |
           wget -qO FFmpeg.tar.gz https://github.com/CSReviser/ffmpeg-build/releases/download/7.1.1/ffmpeg-macos-universal.tar.gz || { echo "Failed to download FFmpeg"; exit 1; }
-          7z e FFmpeg.tar.gz ffmpeg -o./build/CaptureStream2.app/Contents/MacOS/ || { echo "Failed to extract FFmpeg"; exit 1; }
+          7z e FFmpeg.7z ffmpeg -o./build/CaptureStream2.app/Contents/MacOS/ || { echo "Failed to extract FFmpeg"; exit 1; }
           cp CaptureStream2/icon.icns ./build/CaptureStream2.app/Contents/Resources/
           cp CaptureStream2/qss_files/stylesheet-mac.qss ./build/CaptureStream2.app/Contents/MacOS/
 
@@ -542,20 +535,19 @@ jobs:
           mkdir -p build/MacCaptureStream2
           mv build/CaptureStream2.app build/MacCaptureStream2/
           cp -r CaptureStream2/qss_files/License build/MacCaptureStream2/
-         
+          
       - name: Create DMG file
         run: |
-          cd CaptureStream2/build
+          cd build
           hdiutil create -volname CaptureStream2 \
                       -srcfolder MacCaptureStream2 \
                       -ov -format UDZO \
-                      "CaptureStream2-MacOS-qt5-${{ github.event.inputs.yyyymmdd }}.dmg"
-
+                      "CaptureStream2-MacOS-universal-${{ github.event.inputs.yyyymmdd }}.dmg"
 
       - name: Upload DMG to GitHub Release
         uses: softprops/action-gh-release@v2
         with:
-          files: CaptureStream2/build/CaptureStream2-MacOS-qt5-${{ github.event.inputs.yyyymmdd }}.dmg
+          files: CaptureStream2/build/CaptureStream2-MacOS-universal-${{ github.event.inputs.yyyymmdd }}.dmg
           tag_name: ${{ needs.mac_build.outputs.tag }}
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
